name: Build All

on:
  push:
    branches:
      - master
      - test-linux-x64
    paths:
      - .github/workflows/build-all.yml
      - .github/workflows/build.yml
      - .github/workflows/factorial_gmp.c
      - .github/workflows/pi_mpfr.c
  workflow_dispatch:
    inputs:
      gmp-version:
        description: 'GMP Version'
        type: string
        required: false
        default: '6.3.0'
      mpfr-version:
        description: 'MPFR Version'
        type: string
        required: false
        default: '4.2.1'
      build-type:
        description: 'Build type (shared or static)'
        required: true
        default: 'shared'

jobs:
  build_all:
    strategy:
      matrix:
        include:
          - { os: linux,      arch: x64 }
          - { os: linux,      arch: x86 }
          - { os: linux,      arch: arm64 }
          - { os: linux,      arch: arm }
          - { os: linux-musl, arch: x64 }
          - { os: linux-musl, arch: arm64 }
          - { os: win,        arch: x64 }
          - { os: win,        arch: x86 }
          - { os: android,    arch: x64 }
          - { os: android,    arch: arm64 }
          - { os: android,    arch: x86 }
          - { os: android,    arch: arm }
          - { os: osx,        arch: arm64 }
          - { os: osx,        arch: x64 }
          - { os: ios,        arch: arm64 }
          - { os: browser,    arch: wasm }

    uses: ./.github/workflows/build.yml
    with:
      os: ${{ matrix.os }}
      arch: ${{ matrix.arch }}
      gmp-version: ${{ github.event.inputs.gmp-version || '6.3.0' }}
      mpfr-version: ${{ github.event.inputs.mpfr-version || '4.2.1' }}
      build-type: ${{ github.event.inputs.build-type || 'shared' }}