name: Test NuGet

on:
  push:
    branches:
      - master
      - compare-speed
    paths:
      - .github/workflows/test-nuget.yml
      - src/**
  workflow_dispatch:

env:
  NUGET_REGISTRY: https://proget.starworks.cc:88/nuget/test/v3/index.json
  GMP_NUGET_VERSION: 6.3.0-preview.1
  MPFR_NUGET_VERSION: 4.2.1-preview.2
  
jobs:
  test:
    strategy:
      matrix:
        include: 
          # - { os: win, arch: x64 }
          - { os: win, arch: x86 }
          # - { os: win, arch: x64, version: 2019 }
          - { os: win, arch: x86, version: 2019 }
          # - { os: win, arch: x64, version: 2025 }
          - { os: win, arch: x86, version: 2025 }
          # - { os: linux, arch: x64 }
    runs-on: ${{ matrix.os == 'win' && 'windows-latest' || matrix.version == '2019' && 'windows-2019' || matrix.version == '2025' && 'windows-2025' || 'ubuntu-latest' }}
    steps:
    - name: Disable Windows Defender Real-time Protection
      if: matrix.os == 'win'
      run: Set-MpPreference -DisableRealtimeMonitoring $true
      shell: powershell
    - uses: actions/checkout@v4
    # GMP
    - name: Configure NuGet Source
      run: dotnet nuget add source ${{ env.NUGET_REGISTRY }} --name ProGet

    - name: Download GMP Native NuGet
      run: |
        cd src/Sdcb.Arithmetic.Gmp.Tests
        dotnet add package Sdcb.Arithmetic.Gmp.runtime.${{ matrix.os }}-${{ matrix.arch }} -v ${{ env.GMP_NUGET_VERSION }} --no-restore
        cat Sdcb.Arithmetic.Gmp.Tests.csproj
    - name: DotNet Build for GMP
      run: |
        cd src/Sdcb.Arithmetic.Gmp.Tests
        dotnet build -c Debug --runtime ${{ matrix.os }}-${{ matrix.arch }}
    - name: Test GMP
      run: |
        cd src/Sdcb.Arithmetic.Gmp.Tests
        dotnet test -c Debug --no-build --runtime ${{ matrix.os }}-${{ matrix.arch }}
    # MPFR
    - name: Download MPFR Native NuGet
      run: |
        cd src/Sdcb.Arithmetic.Mpfr.Tests
        dotnet add package Sdcb.Arithmetic.Mpfr.runtime.${{ matrix.os }}-${{ matrix.arch }} -v ${{ env.MPFR_NUGET_VERSION }} --no-restore
        cat Sdcb.Arithmetic.Mpfr.Tests.csproj
    - name: DotNet Build for MPFR
      run: |
        cd src/Sdcb.Arithmetic.Mpfr.Tests
        dotnet build -c Debug --runtime ${{ matrix.os }}-${{ matrix.arch }}
    - name: Test MPFR
      run: |
        cd src/Sdcb.Arithmetic.Mpfr.Tests
        dotnet test -c Debug --no-build --runtime ${{ matrix.os }}-${{ matrix.arch }}